### ISSUE TITLE
Duplicate code in %poll and utils/findUser

### ISSUE THREAD

**Issue by fungional** [TheSorton/alice.js#4]
# Current Situation

Some code for finding the item with the highest score (denoted `max` in both sections) has been effectively duplicated.

The code is found in the files:
  + `utils/findUser.js`
  + `commands/misc/poll.js`

# Change

Merge the code into a single file in `utils/`.

# Misc Changes

This would be an opportune time to merge some of the different versions' usage too. Namely, the use of `index` in the return object for `max`, which can instead be replicated using `ties[0]`. Also, consider renaming `ties` to `indices`.

The code in `findUser` makes use of `index`, so it would need to be changed. The code in `poll` uses both `ties` and `index`, so they will need to be changed too.

**Comment by fungional** [comment]
Duplicate(-ish) code found at https://github.com/TheSorton/alice/blob/5f8d8e870693c9d6c6ef179edf79ee3567ba8e0f/commands/misc/poll.js#L72 and https://github.com/TheSorton/alice/blob/5f8d8e870693c9d6c6ef179edf79ee3567ba8e0f/utils/findUser.js#L10

**Comment by oneiricsky** [comment]
See #3
