### ISSUE TITLE
Duplicate code in %image

### ISSUE THREAD

**Issue by fungional** [TheSorton/alice.js#5]
# Current Situation

The function which handles image scrolling by checking reactions applied to the embed created by `%image` duplicates the checking code in the `messageReactionAdd` and `messageReactionRemove` events.

# Change

Pull the code out of the events' logic and into its own function. Then call the function in the event bodies.

**Comment by fungional** [comment]
See https://github.com/TheSorton/alice/blob/5f8d8e870693c9d6c6ef179edf79ee3567ba8e0f/commands/image/image.js#L34 and https://github.com/TheSorton/alice/blob/5f8d8e870693c9d6c6ef179edf79ee3567ba8e0f/commands/image/image.js#L63

**Comment by oneiricsky** [comment]
This issue is no longer relevant with e2b167c, however the issue persists. Closing because `messageReactionAdd` and `messageReactionRemove` are irrelevant.
